---
- name: Test-Playbook
  hosts: test
  remote_user: ubuntu
  become: yes
  vars:
     # path of the ssh key in local 
     ansible_ssh_private_key_file: "/Users/sshrestha/Downloads/Devops-Keys/prom.pem"
  roles:  
    - prometheus
    - grafana
