---
  - name: ensure nginx is at the latest version
    become: true
    apt: name=nginx state=latest

  - name: start nginx
    service:
      name: nginx
      state: stopped
    notify: restart nginx
  
   